### ISSUE TITLE
res2sqlite

### ISSUE THREAD

**Issue by lawrencerenna** [echemdata/galvani#23]
Here is my code:

`from galvani import res2sqlite as r2s

Input_file = 'C012.res'
Output_file = 'new'

r2s.convert_arbin_to_sqlite(Input_file, Output_file)`

Here is the output:

Reading Version_Table...
Error while importing Version_Table

Traceback (most recent call last):
  File "/pithy/code/arbin_import_test.py", line 19, in 
    r2s.convert_arbin_to_sqlite(Input_file, Output_file)
  File "/usr/local/lib/python2.7/dist-packages/galvani/res2sqlite.py", line 417, in convert_arbin_to_sqlite
    mdb_get_data(s3db, input_file, table)
  File "/usr/local/lib/python2.7/dist-packages/galvani/res2sqlite.py", line 397, in mdb_get_data
    mdb_get_data_text(s3db, filename, table)
  File "/usr/local/lib/python2.7/dist-packages/galvani/res2sqlite.py", line 373, in mdb_get_data_text
    mdb_sql.terminate()
UnboundLocalError: local variable 'mdb_sql' referenced before assignment

Can you help me with this error?

Thank you

**Comment by chatcannon** [comment]
Ah, that was silly of me - you see what happens when I refactor without having test coverage...

**Comment by chatcannon** [comment]
Actually it's not quite so silly as all that, it's just that the mdbtools package is not found and the code dealing with the errors isn't prepared to deal with that eventuality

**Comment by lawrencerenna** [comment]
Works great now. Thanks for your help.
